### ISSUE TITLE
Don't rely on `WinMD` files on users' machines to read `WinRT` Metadata

### ISSUE THREAD

**Issue by halildurmus** [halildurmus/winmd#68]
I'm proposing that we generate WinMD files from the official NuGet packages instead of relying on the WinMD files on users' machines to read WinRT Metadata. I got the idea from [windows-rs](https://github.com/microsoft/windows-rs/tree/master/crates/libs/metadata/default) -- which they seem to be doing the same.

The primary reason for this is to get rid of inconsistencies caused by different Windows SDK versions installed on Windows machines. For example, you added support for `Geolocator` to the `win32` package a few months ago. When I ran the `generate.cmd`, several interfaces were not being generated on my machine due to the different Windows SDK versions installed between our machines. Mine had an older version of the Windows SDK and these interfaces required a newer version -- which your machine had.

I already implemented the functionality to generate these files from NuGet packages in [here](https://github.com/halildurmus/winmd/tree/generate) (it also generates `Windows.Win32.winmd` and `Windows.Win32.Interop.dll` files). I wanted to hear your thoughts on this before sending a PR. 

I haven't modified the `MetadataStore` to use the generated `Windows.winmd` for reading WinRT Metadata though (I confirmed that it works). I'm gonna need your help to do this as I'm not very familiar with the code and suspect that there's gonna be some design decisions (e.g. whether to deprecate some functions?) to be made.

WDYT?

**Comment by timsneath** [comment]
That's a really good catch. It's an oversight on my part to date. I run a variety of Windows versions on various machines, so even today it's non-deterministic depending on which machine I happen to be using at the time, which is far from ideal.

We'd have to pick a version that we want to support (most compatible baseline? latest stable Windows version? latest prerelease version?)

These files are smaller than I thought -- 6MB in total, which is interesting given that the Win32 metadata is 16MB. But I think there's an opportunity here to not bundle them at all, as your code shows. But I'm thinking it would be better to move this functionality into the core winmd package, and allow it to either load at runtime or accept a binary file to load from the consuming application, rather than have a separate generator. 

I'll experiment with this: thanks for the issue.
